server.port: 8080

---

spring:
  profiles.active: dev

---

spring:
  profiles: dev
  thymeleaf:
    mode: HTML5
    cache: false
    templates_root: src/main/resources/templates/

---

spring:
  profiles: prod
